- name: Configure frontend 
  hosts: frontend
  become: yes
  tasks:
  - name: Install nginx server
    ansible.builtin.dnf:
      name: nginx
      state: latest
  
  - name: Start and enable Nginx service
    ansible.builtin.service:
      name: nginx
      state: started
      enabled: yes
  
  - name: Delete default website
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: absent

  - name: Create html directory
    ansible.builtin.file:
      path: /usr/share/nginx/html
      state: directory

  - name: Dowmload and extract frontend code
    ansible.builtin.unarchive:
      src: https://expense-builds.s3.us-east-1.amazonaws.com/expense-frontend-v2.zip
      dest: /usr/share/nginx/html
      remote_src: yes
  
  - name: Copy backend configuration
    ansible.builtin.copy:
      src: expense.conf
      dest: /etc/nginx/default.d/expense.conf

  - name: Restart Nginx service
    ansible.builtin.service:
      name: nginx
      state: restarted